from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path, PurePosixPath
from typing import Any, Sequence

from .claude import ClaudeError


WRAPPER_HEADER = "# Generated by Quota Watch."


def _atomic_text_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _read_settings(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ClaudeError(f"WSL Claude settings are not valid JSON: {error}") from error
    if not isinstance(payload, dict):
        raise ClaudeError("WSL Claude settings root must be a JSON object.")
    return payload


def _contains_ingest_command(content: str) -> bool:
    lowered = content.lower()
    return "claude-ingest" in lowered and any(
        marker in lowered for marker in ("quota.exe", "quota-watch", "quota_watch")
    )


def _local_script_path(command: str, local_home: Path, linux_home: str) -> Path | None:
    try:
        arguments = shlex.split(command)
    except ValueError:
        return None
    home = PurePosixPath(linux_home)
    for argument in reversed(arguments):
        if argument.startswith("~/"):
            candidate = home / argument[2:]
        elif argument.startswith("/"):
            candidate = PurePosixPath(argument)
        else:
            continue
        try:
            relative = candidate.relative_to(home)
        except ValueError:
            continue
        return local_home.joinpath(*relative.parts)
    return None


def configure_wsl_files(
    local_home: Path,
    linux_home: str,
    ingest_command: str,
    dry_run: bool = False,
) -> tuple[bool, str, dict[str, Any]]:
    settings_path = local_home / ".claude" / "settings.json"
    settings = _read_settings(settings_path)
    current = settings.get("statusLine")
    if current is not None and not isinstance(current, dict):
        raise ClaudeError("WSL Claude statusLine must be a JSON object.")

    current_entry = dict(current or {})
    existing_command = current_entry.get("command")
    if existing_command is not None and not isinstance(existing_command, str):
        raise ClaudeError("WSL Claude statusLine command must be a string.")

    if existing_command and _contains_ingest_command(existing_command):
        return False, "WSL Claude statusLine already forwards quota data to Windows.", current_entry

    if existing_command:
        existing_script = _local_script_path(existing_command, local_home, linux_home)
        if existing_script and existing_script.is_file():
            try:
                content = existing_script.read_text(encoding="utf-8")
            except OSError as error:
                raise ClaudeError(f"Could not inspect existing WSL statusLine script: {error}") from error
            if _contains_ingest_command(content):
                return False, "WSL Claude statusLine already forwards quota data to Windows.", current_entry

    wrapper_linux = str(PurePosixPath(linux_home) / ".claude" / "quota-watch-statusline.sh")
    wrapper_local = local_home / ".claude" / "quota-watch-statusline.sh"
    if wrapper_local.exists():
        content = wrapper_local.read_text(encoding="utf-8")
        if not content.startswith(WRAPPER_HEADER):
            raise ClaudeError(f"Refusing to replace unrelated WSL file: {wrapper_linux}")

    lines = [
        WRAPPER_HEADER,
        "# Preserves an existing Claude status line while updating the Windows cache.",
        "input=$(cat)",
        f"quota_output=$(printf '%s' \"$input\" | {ingest_command} 2>/dev/null || true)",
    ]
    if existing_command:
        lines.append(f"printf '%s' \"$input\" | bash -c {shlex.quote(existing_command)}")
    else:
        lines.append("printf '%s' \"$quota_output\"")
    wrapper_content = "\n".join(lines) + "\n"

    entry = current_entry
    entry["type"] = "command"
    entry["command"] = f"bash {shlex.quote(wrapper_linux)}"
    if not existing_command:
        entry.setdefault("refreshInterval", 5)

    updated = dict(settings)
    updated["statusLine"] = entry
    if dry_run:
        return True, f"Dry run: WSL Claude statusLine can be connected through {wrapper_linux}.", entry

    settings_path.parent.mkdir(parents=True, exist_ok=True)
    if settings_path.exists():
        backup = settings_path.with_name(settings_path.name + ".quota-watch-wsl.bak")
        if not backup.exists():
            shutil.copy2(settings_path, backup)
    _atomic_text_write(wrapper_local, wrapper_content)
    _atomic_text_write(settings_path, json.dumps(updated, ensure_ascii=False, indent=2) + "\n")
    return True, f"Configured WSL Claude statusLine through {wrapper_linux}.", entry


def _run_wsl(arguments: Sequence[str], distro: str | None = None) -> str:
    if os.name != "nt":
        raise ClaudeError("--wsl is available only from Windows.")
    executable = shutil.which("wsl.exe")
    if not executable:
        raise ClaudeError("wsl.exe was not found.")
    command = [executable]
    if distro:
        command.extend(["--distribution", distro])
    command.extend(["--exec", *arguments])
    creation_flags = subprocess.CREATE_NO_WINDOW
    try:
        completed = subprocess.run(
            command,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
            creationflags=creation_flags,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise ClaudeError(f"Could not query WSL: {error}") from error
    if completed.returncode != 0:
        detail = completed.stderr.strip() or completed.stdout.strip() or f"exit code {completed.returncode}"
        raise ClaudeError(f"WSL command failed: {detail}")
    return completed.stdout.strip()


def _discover_ingest_command(distro: str | None) -> tuple[Path, str, str]:
    linux_home = _run_wsl(["printenv", "HOME"], distro)
    if not linux_home.startswith("/"):
        raise ClaudeError("Could not determine the WSL home directory.")
    local_home_text = _run_wsl(["wslpath", "-w", linux_home], distro)
    local_home = Path(local_home_text)

    launcher = shutil.which("quota") or shutil.which("quota-watch")
    if launcher:
        linux_launcher = _run_wsl(["wslpath", "-u", str(Path(launcher).resolve())], distro)
        ingest_command = f"{shlex.quote(linux_launcher)} claude-ingest"
    else:
        linux_python = _run_wsl(["wslpath", "-u", str(Path(sys.executable).resolve())], distro)
        ingest_command = f"{shlex.quote(linux_python)} -m quota_watch claude-ingest"
    return local_home, linux_home, ingest_command


def configure_wsl_statusline(
    dry_run: bool = False,
    distro: str | None = None,
) -> tuple[bool, str, dict[str, Any]]:
    local_home, linux_home, ingest_command = _discover_ingest_command(distro)
    return configure_wsl_files(local_home, linux_home, ingest_command, dry_run=dry_run)
